version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./backend/vendor:/var/www/vendor
      - ./backend/storage:/var/www/storage
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./backend/nginx:/etc/nginx/conf.d
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: >
      sh -c "yarn next build && yarn next start"
    image: nextjs_app
    container_name: nextjs_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./frontend:/app

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
